#!/bin/bash

# -lgsl/-lgslcblas: gsl/*.h
#              -lm: math.h
#               -g: outputting line number when using valgrind
#               -w: inhibit all warning messages

gcc -std=c99 -o mlr bayesMLR.c -L/home/luiarthur/Libs/gsl/lib -I/home/luiarthur/Libs/gsl/include -lgsl -lgslcblas -lm -w -g
